<?php

namespace App\Service;

use GuzzleHttp\Client;

class GuzzleWrapperService extends Client
{
    public function post($url = null, array $options = [])
    {
        return parent::post($url, $options); // TODO: Change the autogenerated stub
    }

}
