<?php

declare(strict_types=1);

namespace App\Test;

use App\Dto\TokenResponseDto;
use App\Service\GuzzleWrapperService;
use PHPUnit\Framework\TestCase;

require __DIR__ . '/../../vendor/autoload.php';

class FixablyApiServiceTest extends TestCase
{
    /**
     * @test
     */
    public function testFetchToken()
    {
        $service = $this->getFixablyApiService();

        $r = $service->fetchToken();
    }

    public function getGuzzleWrapperService(array $options = []): GuzzleWrapperService
    {
        return new class ($options) extends GuzzleWrapperService {

            public function post($url = null, array $options = [])
            {
                return parent::post($url, $options); // TODO: Change the autogenerated stub
            }
        };
    }

}
